import axios from "axios";
import Cookies from "js-cookie";
import { ReactNode } from "react";
import { Montserrat } from "next/font/google";

import Header from "../components/Main/Header";

import "/src/style/index.scss";


const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

axios.defaults.headers.common["x-api-key"] = Cookies.get("userToken");
axios.defaults.baseURL = "https://api.stroykovcheg.ru/api/";

export default function RootLayout({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <Header />
        {children}
        <script src="//cdn.jsdelivr.net/npm/eruda"></script>
        <script>eruda.init();</script>
      </body>
    </html>
  );
}
