import axios from "axios";
import Cookies from "js-cookie";
import { ReactNode } from "react";
import { Roboto } from "next/font/google";

import Header from "../components/main/Header";
import Footer from "../components/main/Footer";

import "/src/style/index.scss";
import classNames from "../functions/classNames";


const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["100", "300", "400", "500", "700"]
});

axios.defaults.headers.common["x-api-key"] = Cookies.get("userToken");
axios.defaults.baseURL = "https://api.stroykovcheg.ru/api/";

export default function RootLayout({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className="container">
        <Header />
        <div className={classNames("content")}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
